import type { Metadata } from "next";

import ThemesProvider from "@/context/ThemeContext";

import "./globals.css";

export const metadata: Metadata = {
    title: "E-Commerce",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemesProvider>
                    {children}
                </ThemesProvider>
            </body>
        </html>
    );
}
