import type { Metadata } from "next";

import ThemesProvider from "@/context/ThemeContext";

import "./globals.css";


import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

export const metadata: Metadata = {
    title: "E-Commerce",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="bg-bg-base">
                <ThemesProvider>
                    {children}
                </ThemesProvider>
            </body>
        </html>
    );
}
